### ISSUE TITLE
v2.1 not tagged as v2

### ISSUE THREAD

**Issue by XnS** [Vankka/pr-target-branch-action#3]
Hi,

not sure if it's intentional, but the v2 tag does not point to the v2.1 tag, and therefore the fix for issue #1 is not available when using `Vankka/pr-target-branch-action@v2`.

According to https://github.com/actions/toolkit/blob/main/docs/action-versioning.md#recommendations it's best practice to update the major version tag if a new minor version has been published.
> Make the new release available to those binding to the major version tag: Move the major version tag (v1, v2, etc.) to point to the ref of the current release. This will act as the stable release for that major version. You should keep this tag updated to the most recent stable minor/patch release.

### How to repeat
Action definition:
```
name: Test

on:
  pull_request_target: # Please read https://securitylab.github.com/research/github-actions-preventing-pwn-requests/ before using
    types: [opened, edited]

jobs:
  check-branch:
    runs-on: [ self-hosted ]
    steps:
      - uses: Vankka/pr-target-branch-action@v2
```

Log:
```
2022-12-07T11:16:36.3820837Z Download action repository 'Vankka/pr-target-branch-action@v2' (SHA:69ab6dd5c221de3548b3b6c4d102c1f4913d3baa)
```

Tags:
v2: 69ab6dd
v2.1: def32ec
